### PR TITLE
[FIX]sale_stock_ux: cancel remaining with returned quantities

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/875).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc r-

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#984

**Pull request closed without merging**
