### PR TITLE
[MIG] sale_exception_partner_state: Migration to 15.0

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/540).

**Review by nicomacr — DISMISSED** [review]
LGTM

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests p=0

**Pull request closed without merging**
