### PR TITLE
[13.0] [FIX] sale_stock_ux: Show return quantity when the order is done or sale.

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
@jjscarafia check this out?

It's related to  changes in https://github.com/ingadhoc/purchase/pull/122

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/447).

**Review by jjscarafia — APPROVED** [review]

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You can't review+.

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
roboadhoc rebase-merge

**Comment by roboadhoc** [comment]
Merge method set to rebase and merge, using the PR as merge commit message

**Comment by nicomacr** [comment]
roboadhoc r-

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc review-

**Comment by nicomacr** [comment]
roboadhoc retry

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. Retry makes no sense when the PR is not in error.

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
roboadhoc review+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
roboadhoc review-

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
@roboadhoc r-

**Comment by nicomacr** [comment]
robodoo r+ 👍🏻

**Pull request merged**
