### PR TITLE
[FIX] sale_stock_ux: arguments of _bom_find method changed due to migration

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/577).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti, you may want to rebuild or fix this PR as it has failed CI.

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/personalizations r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/personalizations p=0

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Pull request closed without merging**
