### PR TITLE
[FW][IMP] sale_ux: Improve the bring or not notes from sol to invoice lines.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
We create a parameter to be optional brings the notes to the invoice lines from the sale order lines, when create the invoice.

Forward-Port-Of: ingadhoc/sale#462

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/463).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc  override=ci/oba_without_tests

**Pull request merged**
