### PR TITLE
[IMP]sale_ux: allow any user on invoice with group_allow_any_user_as_salesman

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/695).

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#699

**Pull request closed without merging**
