### PR TITLE
[FW][FIX]sale_barcode: order line creation on scan

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#631

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/632).

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jok-adhoc** [comment]
@matiasperalta1 mati, vos tenes idea del modulo este?

**Comment by jok-adhoc** [comment]
@matiasperalta1 ping

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
