### PR TITLE
[IMP] portal_sale_distributor: block the so order if the configuratio…

### PR DESCRIPTION
**Pull request by lav-adhoc**
…n is set

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/873).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#876

**Pull request closed without merging**
