### PR TITLE
[FW][FIX] portal_sale_distributor: Fix price compute calculation for Portal's

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
### Ticket 47770

Forward-Port-Of: ingadhoc/sale#490

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/491).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia

ci/oba_without_tests failed on this forward-port PR

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+ override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
