### PR TITLE
[ADD][IMP]sale_dispatch_with_prepaid

### PR DESCRIPTION
**Pull request by jok-adhoc**
For prepaid type's sales, allows dispatch even though the payment is not complete.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/587).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#598

**Pull request closed without merging**
