### PR TITLE
[FIX] sale_stock_ux: revert compute_invoice_status

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1069).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1070

**Pull request closed without merging**
