### PR TITLE
[IMP] sale_ux: change in portal quotation payment terms

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/787).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#789

**Pull request closed without merging**
