### PR TITLE
[MIG] sale_barcode: Migration to 16.0

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/674).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc override ci/runbot-oba

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
