### PR TITLE
[FW][ADD] portal_distributor_sale_exception: add a record rule to portal …

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…user

Forward-Port-Of: ingadhoc/sale#720

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/725).

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request merged**
