### PR TITLE
[FIX] sale_exception_credit_limit: take into account the amounts retu…

### PR DESCRIPTION
**Pull request by lef-adhoc**
…rned

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/833).

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#836

**Pull request closed without merging**
