### PR TITLE
[FW][IMP] sale_ux: improvement in the search for action sale history

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#892

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/894).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 cherrypicking of pull request ingadhoc/sale#892 failed.

stdout:
```
Auto-merging sale_ux/views/sale_order_views.xml
Auto-merging sale_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_ux/__manifest__.py

```

stderr:
```
18:48:18.360323 git.c:444               trace: built-in: git cherry-pick d8d00fdfc57eecb3ae3ddb8f72ce9eba43f4a89a
error: could not apply d8d00fdf... [IMP] sale_ux: improvement in the search for action sale history
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by matiasperalta1** [comment]
@fw-bot-adhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Pull request closed without merging**
