### PR TITLE
[FW][FIX]sale_order_type_automation:no create payment without payment_ato…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…mation

Ticket: 51274. No create payment if partment_atomation is 'none'

Forward-Port-Of: ingadhoc/sale#529

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/530).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
