### PR TITLE
[FW][FIX]sale_three_discounts: without disc policy on website

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#793

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/794).

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jok-adhoc** [comment]
@matiasperalta1 cierro este fp, no? El sale_three_disc era el que se estaba viendo si se hacia alugn refactor o no. Sino lo dejamos abierto pero queda el comentario

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jok-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
