### PR TITLE
[FIX] sale_ux: changes in compute price unit

### PR DESCRIPTION
**Pull request by lav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/811).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#812

**Pull request closed without merging**
