### PR TITLE
[FW][FIX]sale_order_type_automation_stock_voucher

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
add sale.order methods in sale_order_type_automation_stock_voucher and fix the methods in sale_order_type_automation

Forward-Port-Of: ingadhoc/sale#945

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/964).

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by matiasperalta1** [comment]
@fw-bot-adhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Pull request closed without merging**
