### PR TITLE
[IMP] hide fields in product.template tree views for group_portal_distributor

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/600).

**Review by JoelZilli — APPROVED** [review]

**Comment by JoelZilli** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @JoelZilli this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#606

**Pull request closed without merging**
