### PR TITLE
[FW][IMP] portal_sale_distributor: change message when a sale is not conf…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…irmed

Forward-Port-Of: ingadhoc/sale#754

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/791).

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jok-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jok-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jok-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jok-adhoc** [comment]
@lav-adhoc esto lo podes ver?

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by lav-adhoc** [comment]
@fw-bot-adhoc

**Pull request closed without merging**
