### PR TITLE
[FW][FIX] sale_ux: Fix in action_post from account_move when having a downpayment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#1060

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1063).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this PR targets 18.0 and is the last of the forward-port chain containing:
* ingadhoc/sale#1061

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
