### PR TITLE
[FIX] sale_order_validity: fix in sale_order_view

### PR DESCRIPTION
**Pull request by lav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/769).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#770

**Pull request closed without merging**
