### PR TITLE
[FIX] sale_ux: backport 15 to 13 user_id allow not only internal users

### PR DESCRIPTION
**Pull request by matiasperalta1**
This funcionality appear in 15 with this PR https://github.com/ingadhoc/sale/commit/7266218b4392539be1b271497022e977bcda2d83#diff-f47031deb7c59bdf951c3a93001c27a489d411cb61bd9858db1e6d8e601ac342R1

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/660).

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#663

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#663

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#663

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#663

**Pull request closed without merging**
