### PR TITLE
[FIX] sale_stock_ux: 'delivery_status' appears after 'invoice_status' on sale order tree view

### PR DESCRIPTION
**Pull request by jue-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1000).

**Comment by JrAdhoc** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Comment by fw-bot-adhoc** [comment]
@jue-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1027

**Pull request closed without merging**
