### PR TITLE
[FW][ADD] sale_stock_ux: force to update invoice report view

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
to avoid problem with _get_invoiced_lot_values

Forward-Port-Of: ingadhoc/sale#608

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/609).

**Comment by fw-bot-adhoc** [comment]
@zaoral cherrypicking of pull request ingadhoc/sale#608 failed.

stdout:
```
Auto-merging sale_stock_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_stock_ux/__manifest__.py

```

stderr:
```
17:59:57.963505 git.c:439               trace: built-in: git cherry-pick bfd6cab6618b7439e5b7ef4a6372e37c06538f65
error: could not apply bfd6cab6... [ADD] sale_stock_ux: force to update invoice report view
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc retry

**Comment by zaoral** [comment]
Hi Nico!
I hope you are doing well.

I have this old FW that was not merged.
I am trying to merge it now but the new mergebot does not recognize.
Please could you help me here to add this PR to the new mergebot?

Best Regards
@nicomacr

**Comment by zaoral** [comment]
superseded by https://github.com/ingadhoc/sale/pull/637

**Pull request closed without merging**
