### PR TITLE
[FW][FIX] sale_stock_ux: revert compute_invoice_status

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#1069

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1070).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @mav-adhoc cherrypicking of pull request ingadhoc/sale#1069 failed.

stdout:
```
Auto-merging sale_stock_ux/models/sale_order_line.py
CONFLICT (content): Merge conflict in sale_stock_ux/models/sale_order_line.py

```

stderr:
```
11:32:27.912564 git.c:444               trace: built-in: git cherry-pick 379901100d74799110d36ec213248ef3a4cc6350
error: could not apply 37990110... [FIX] sale_stock_ux: revert compute_invoice_status
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by mav-adhoc** [comment]
@matiasperalta1 Mati! Entiendo que vamos a mezclar este Fwp. Fijate si lo corregis y avisame para que lo mezcle!

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
