### PR TITLE
[REM] sale_quotation_ux

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/528).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
