### PR TITLE
[MIG] sale_order_lot_selection_ux: Migration to 17.0

### PR DESCRIPTION
**Pull request by cem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/834).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@cem-adhoc @matiasperalta1 because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
