### PR TITLE
[MIG] sale_timesheet_ux: Migration to 17.0

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/778).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@ALopez-Adhoc @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jcadhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: you are not allowed to override this status.

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
