### PR TITLE
[REF] sale_order_type_ux: compute of team_id

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/804).

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#807

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#807

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#807

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#807

**Pull request closed without merging**
