### PR TITLE
[FW][13.0] [ADD] sale_gathering: Add new module sale_gathering

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#432

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/524).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
