### PR TITLE
[FIX] sale_gathering: fix in constrains and decimals in invoice

### PR DESCRIPTION
**Pull request by lef-adhoc**
#76699

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/853).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#869

**Pull request closed without merging**
