### PR TITLE
[FW][FIX] sale_stock_ux: context error in nested button actions

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
This is to avoid context errors in other odoo actions.

Forward-Port-Of: ingadhoc/sale#534

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/536).

**Comment by fw-bot-adhoc** [comment]
Ping @Bruno-Zanotti, @nicomacr
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @Bruno-Zanotti, @nicomacr

ci/oba_without_tests failed on this forward-port PR

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Pull request closed without merging**
