### PR TITLE
[ADD]sale_require_terms_and_conditions

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/692).

**Comment by matiasperalta1** [comment]
@roboadhoc r+ override = ci/runbot-oba

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
