### PR TITLE
[FIX] sale_ux: adjustment in cron to cancel old quotation

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/976).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#979
- ingadhoc/sale#980

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#979
- ingadhoc/sale#980

**Pull request closed without merging**
