### PR TITLE
[FIX] sale_ux: Fix in returning price_unit when having tax excluded

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/999).

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1013

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1013

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1013

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1013

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1026

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1026

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1026

**Pull request closed without merging**
