### PR TITLE
[FW][FIX] sale_ux: adjustment in cron to cancel old quotation

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#976

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/980).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc this PR targets 18.0 and is the last of the forward-port chain containing:
* ingadhoc/sale#979

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
