### PR TITLE
[FIX] crm_teams_ux: domain of user_id fixed

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/640).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @vib-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
