### PR TITLE
Revert "[FIX] report quotation: Fix when image column is displayed"

### PR DESCRIPTION
**Pull request by matiasperalta1**
This reverts commit 87daf760f6d97e325ba9ed3fd183fa24b2ffd2c4.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/628).

**Comment by matiasperalta1** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#629

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#629

**Pull request closed without merging**
