### PR TITLE
[FW][IMP] portal_sale_distributor: block the so order if the configuratio…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…n is set

Forward-Port-Of: ingadhoc/sale#873

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/876).

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 cherrypicking of pull request ingadhoc/sale#873 failed.

stdout:
```
Auto-merging portal_sale_distributor/__manifest__.py
CONFLICT (content): Merge conflict in portal_sale_distributor/__manifest__.py

```

stderr:
```
15:47:19.504235 git.c:444               trace: built-in: git cherry-pick 57b98f892c6793d2c0f9ba8b448bab2d9f4f187b
error: could not apply 57b98f89... [IMP] portal_sale_distributor: block the so order if the configuration is set
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by lav-adhoc** [comment]
Cerramos este PR ya que le módulo no se incializo en 17. Cuando se inicie, en caso de que lo querramos migrar, ya va a traer el cambio que aplicaba este pr

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
