### PR TITLE
[FIX] sale_ux: modifying the discount, adding lines and changing the …

### PR DESCRIPTION
**Pull request by lef-adhoc**
…price list of a blocked sales order is prevented.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1048).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1053
- ingadhoc/sale#1054

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1053
- ingadhoc/sale#1054

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1053
- ingadhoc/sale#1054

**Pull request closed without merging**
