### PR TITLE
[FIX]sale_three_discounts: without disc policy on website

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/793).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#794

**Pull request closed without merging**
