### PR TITLE
[FW][REF] sale_order_type_ux: compute of team_id

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#804

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/807).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
