### PR TITLE
[MIG] sale_order_type_user_default: Migration to 17.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/750).

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot/oba

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
mezclamos igual porque el error de runbot estaría arreglado en sale_order_type

**Pull request merged**
