### PR TITLE
[FW][ADD] sale_gathering_automation: add new module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#1034
Forward-Port-Of: ingadhoc/sale#973

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1052).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 ci/runbot-oba failed on this forward-port PR

**Comment by lef-adhoc** [comment]
Falta mezclar gathering

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
