### PR TITLE
[ADD]sale_timesheet_ux: README

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1031).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1032

**Pull request closed without merging**
