### PR TITLE
[FIX] crm_survey: answer token vinculation fixed

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/687).

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
Merge despite of red sign on runbot because it's not related to the change

**Pull request closed without merging**
