### PR TITLE
[ADD] sale_stock_ux: force to update invoice report view

### PR DESCRIPTION
**Pull request by zaoral**
to avoid problem with _get_invoiced_lot_values

X-original-commit: f480fa06a126167bb236e362d58096419295408e

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/637).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#638

**Pull request closed without merging**
