### PR TITLE
[IMP] sale_order_type_ux: view modification

### PR DESCRIPTION
**Pull request by cem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/839).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#884

**Pull request closed without merging**
