### PR TITLE
[ADD] sale_timesheet_ux: rst syntax

### PR DESCRIPTION
**Pull request by zaoral**
found warning and runbot when trying to merge another repo pr.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/586).

**Comment by zaoral** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you are not allowed to override this status.

**Comment by zaoral** [comment]
@nicomacr 
Hi Nico, please could you help me to merge this pr?
It resolves some of the warnings in runbot 15.
I can't merge it because we have also another warning that Vir is already working on it.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc r-

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@zaoral Done!

**Comment by zaoral** [comment]
@nicomacr 
thanks!

**Pull request closed without merging**
