### PR TITLE
[MIG] sale_gathering: Migration to 16.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/710).

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @lef-adhoc. I'm afraid I can't do that.

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @lef-adhoc. I'm afraid I can't do that.

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#771

**Pull request closed without merging**
