### PR TITLE
[FW][IMP] sale_ux: change in portal quotation payment terms

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#787

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/789).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc cherrypicking of pull request ingadhoc/sale#787 failed.

stdout:
```
Auto-merging sale_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_ux/__manifest__.py

```

stderr:
```
16:14:55.457101 git.c:444               trace: built-in: git cherry-pick 82578ded5e33c1055b092aba16301f676b0f6c0e
error: could not apply 82578ded... [IMP] sale_ux: change in portal quotation payment terms
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by matiasperalta1** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
