### PR TITLE
[REF] sale_order_type_automation: adding try/except to avoid rollback

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/826).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#837

**Pull request closed without merging**
