### PR TITLE
[REF] sale_quotation_products: add comment

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/781).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#783

**Pull request closed without merging**
