### PR TITLE
[FIX] sale_ux: fix button update_price

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/619).

**Review by jok-adhoc — APPROVED** [review]

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jok-adhoc: I must know your email before you can review PRs. Please contact an administrator.

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/619).

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
