### PR TITLE
[IMP] sale_ux: buttons modification

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/559).

**Review by nicomacr — DISMISSED** [review]

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
