### PR TITLE
[FIX] report quotation: Fix when image column is displayed

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/622).

**Review by jok-adhoc — APPROVED** [review]

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jok-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#623

**Pull request closed without merging**
