### PR TITLE
[MIG] sale_three_discounts: Migration to 16.0

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/604).

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@JrAdhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by JrAdhoc** [comment]
@roboadhoc r+ override=ci/oba_without_tests p=0

**Comment by roboadhoc** [comment]
@JrAdhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @JrAdhoc:
- this PR is already reviewed, reviewing it again is useless.
- you are not allowed to override this status.

**Pull request closed without merging**
