### PR TITLE
[FIX] FIX sale report: Request is not available in cron excutions. (E…

### PR DESCRIPTION
**Pull request by filoquin**
….G. SO payment confirmation)

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/634).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#635

**Comment by fw-bot-adhoc** [comment]
@filoquin @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#635

**Pull request closed without merging**
