### PR TITLE
[FIX] sale_ux: correction to find the invoices even if the company is…

### PR DESCRIPTION
**Pull request by lef-adhoc**
… not selected

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/806).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#808

**Pull request closed without merging**
