### PR TITLE
[FIX]sale_barcode: order line creation on scan

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/631).

**Review by jok-adhoc — APPROVED** [review]

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#632

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#632

**Pull request closed without merging**
