### PR TITLE
[NEW]sale_loyalty_ux: new module

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/775).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#978

**Pull request closed without merging**
