### PR TITLE
[MIG] sale_require_ref: Migration to 13.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/464).

**Comment by nicomacr** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
