### PR TITLE
[REM] sale_quotation_products: deprecated module

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/861).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti @mav-adhoc linked pull request(s) ingadhoc/product#647 not ready. Linked PRs are not staged until all of them are ready.

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
