### PR TITLE
[FW][FIX] sale_three_discounts: recalculation when changing pricelist

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#1064

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1067).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc cherrypicking of pull request ingadhoc/sale#1064 failed.

stdout:
```
Auto-merging sale_three_discounts/models/sale_order.py
CONFLICT (content): Merge conflict in sale_three_discounts/models/sale_order.py

```

stderr:
```
14:24:01.345857 git.c:444               trace: built-in: git cherry-pick 2711130eb515c14e016ebc75bc5aa1c42cf71363
error: could not apply 2711130e... [FIX] sale_three_discounts: recalculation when changing pricelist
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by jjscarafia** [comment]
mezclamos igual porque falla al no poder construir repo privado y publico en mismo batch
otro pr https://github.com/ingadhoc/demo/pull/150

**Pull request closed without merging**
