### PR TITLE
[FW][FIX] sale_ux: in sale report request is not available in cron excutions

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#746

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/747).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@maq-adhoc Filo! Después avisame si queres que veamos este FW o lo ves vos

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
