### PR TITLE
[FW][ADD] sale_stock_ux: force to update invoice report view

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
to avoid problem with _get_invoiced_lot_values

X-original-commit: f480fa06a126167bb236e362d58096419295408e

Forward-Port-Of: ingadhoc/sale#637

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/638).

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro cherrypicking of pull request ingadhoc/sale#637 failed.

stdout:
```
Auto-merging sale_stock_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_stock_ux/__manifest__.py

```

stderr:
```
14:51:18.251531 git.c:444               trace: built-in: git cherry-pick 3cb4c66d15bdbf32a8557f8b42b67e0082829ca1
error: could not apply 3cb4c66d... [ADD] sale_stock_ux: force to update invoice report view
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by nicomacr** [comment]
@zaoral is this PR really needed on 16? In case yes should be fixed and merged

**Comment by zaoral** [comment]
thank you for the review @nicomacr 
indeed not needed.
I will close the pr.

Best Regards

**Pull request closed without merging**
