### PR TITLE
[FIX] sale_ux: Check fiscal_position

### PR DESCRIPTION
**Pull request by dal-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1017).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#1020

**Pull request closed without merging**
