### PR TITLE
[ADD] sale_stock_ux: force to update invoice report view

### PR DESCRIPTION
**Pull request by zaoral**
to avoid problem with _get_invoiced_lot_values

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/608).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#609

**Pull request closed without merging**
