### PR TITLE
[FIX] sale_ux: fixed that when a price list is changed and the sales …

### PR DESCRIPTION
**Pull request by lef-adhoc**
…order is not saved and there are optional products the lines of the sales order are deleted.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/868).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#872

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#872

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#872

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#872

**Pull request closed without merging**
