### PR TITLE
[FIX] sale_quotation_products: make all fields not editable

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/654).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@vib-adhoc @jcadhoc linked pull request(s) ingadhoc/product#494 not ready. Linked PRs are not staged until all of them are ready.

**Comment by roboadhoc** [comment]
@vib-adhoc @jcadhoc linked pull request(s) ingadhoc/product#494 not ready. Linked PRs are not staged until all of them are ready.

**Comment by jjscarafia** [comment]
se mezcla igual, el error de runbot es por otro módulo

**Pull request merged**
