### PR TITLE
[FIX] sale_ux: in sale report request is not available in cron excutions

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/746).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#747

**Pull request closed without merging**
