### PR TITLE
[IMP] sale_gathreing: add fields in quotation report

### PR DESCRIPTION
**Pull request by lav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/867).

**Comment by JrAdhoc** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @JrAdhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#931

**Pull request closed without merging**
