### PR TITLE
[FW][FIX] sale_ux: Fix in returning price_unit when having tax excluded

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#999

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1013).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc cherrypicking of pull request ingadhoc/sale#999 failed.

stdout:
```
Auto-merging sale_ux/models/__init__.py
CONFLICT (content): Merge conflict in sale_ux/models/__init__.py
Auto-merging sale_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_ux/__manifest__.py
Auto-merging sale_ux/README.rst
CONFLICT (content): Merge conflict in sale_ux/README.rst

```

stderr:
```
17:17:11.691475 git.c:444               trace: built-in: git cherry-pick e71a51805df1f6eec5113eba0b2f38e7bc9b5db2
error: could not apply e71a5180... [FIX] sale_ux: Fix in returning price_unit when having tax excluded
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by feg-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
