### PR TITLE
[FW][FIX] sale_ux: changes in compute price unit

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#811

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/812).

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lav-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
