### PR TITLE
[FW][IMP] sale_order_type_ux: view modification

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/sale#839

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/884).

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @matiasperalta1 cherrypicking of pull request ingadhoc/sale#839 failed.

* 6c5daa3ae6163beb340cf423890c8235b06b85dc <- on this commit
* 10775ae4fdbaea180a1790ce9969326885e816f6
* a4c3fed4000a3a2a94647497e3c73f773d925a4d

stdout:
```
Auto-merging sale_order_type_invoice_policy/i18n/es.po
Auto-merging sale_order_type_invoice_policy/__manifest__.py
CONFLICT (content): Merge conflict in sale_order_type_invoice_policy/__manifest__.py

```

stderr:
```
16:28:41.525395 git.c:444               trace: built-in: git cherry-pick 6c5daa3ae6163beb340cf423890c8235b06b85dc
error: could not apply 6c5daa3a... [IMP] sale_order_type_invoice_policy: view modification
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@cem-adhoc @matiasperalta1 because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by matiasperalta1** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
