### PR TITLE
[ADD]sale_stock_ux: Mass cancellation of remaining quantities

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/617).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/617).

**Comment by matiasperalta1** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: this PR is already reviewed, reviewing it again is useless.

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/sale#626

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#626

**Pull request closed without merging**
