### PR TITLE
[FIX]sale_Stock_ux: revert compute_invoice_status

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/996).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#997

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#997

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#997

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#997

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#997

**Pull request closed without merging**
