### PR TITLE
[FIX] sale_ux: Set positive quantities for invoice lines in credit notes

### PR DESCRIPTION
**Pull request by lef-adhoc**
Previously, when a product was returned with a 100% discount, and the invoice was converted to a credit note using the `action_switch_invoice_into_refund_credit_note()` method, the quantities of the invoice lines remained negative. This caused inaccuracies in the calculation of invoiced quantities in the sales order.

This commit addresses the issue by ensuring that the quantities of the invoice lines are set to their absolute values when the invoice is converted into a credit note.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/748).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#751

**Pull request closed without merging**
