### PR TITLE
[FIX] sale_order_type_ux: migration error

### PR DESCRIPTION
**Pull request by zaoral**
_onchange_currency does not exit anymore on account.move use the _compute_currency_rate method instead

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/676).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @mem-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@zaoral @mem-adhoc linked pull request(s) ingadhoc/account-financial-tools#419 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
