### PR TITLE
[IMP] portal_sale_distributor: hide fields in product_tremplate view

### PR DESCRIPTION
**Pull request by lav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/713).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#716

**Pull request closed without merging**
