### PR TITLE
[ADD] portal_sale_distributor_barcode: add acces rule for portal distributor

### PR DESCRIPTION
**Pull request by lav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/719).

**Comment by matiasperalta1** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Comment by fw-bot-adhoc** [comment]
@lav-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/sale#737

**Pull request closed without merging**
